### ISSUE TITLE
Game server closes

### ISSUE THREAD

**Issue by Luckyme66** [SMRT-WSU/cards#7]
When four connections are made, the server tops listening: for new connections or for messages from the old ones. It stops sending as well. I just shuts down.

**Comment by incarnadined** [comment]
It is supposed to limit to 4

**Comment by incarnadined** [comment]
are you saying this is a problem?

**Comment by Luckyme66** [comment]
I know, but it doesn't allow the four to then talk to it.

**Comment by incarnadined** [comment]
In my chat app, 4 can connect and talk fine

**Comment by Luckyme66** [comment]
Yeah, it's because I changed some stuff

**Comment by Luckyme66** [comment]
If you run it in powershell instead of the python terminal, then it doesn't end the script but the '4players' message still doesn't send.

**Comment by incarnadined** [comment]
Looking at the gameserver code now, I feel like I can see multiple errors that prevent it from running

**Comment by incarnadined** [comment]
Surely it doesn't send the 4players message because it runs into an error before that

**Comment by Luckyme66** [comment]
Yup. I haven't really tried to solve the problem in more ways than messing around with a few things. It's nearly solved now (I hope).

**Comment by incarnadined** [comment]
I don't know what you've updated offline, `if len(clients) >= 4:
            else:
                for sock in clients:
                    sock.send(bytes('PickOrder,askinput','utf8'))
                    order = sock.recv(buffer).decode(utf8)
                    break
                Client.broadcast('4players','event')`but the indentation is messed up

**Comment by Luckyme66** [comment]
I was midway through editing that. Yeah, that was broken. The next time I commit that should be fixed.
